CREATE TABLE ORDER_ITEMS (
  OrderID NUMBER NOT NULL,
  ProductID NUMBER NOT NULL,
  Quantity NUMBER NOT NULL,
  PRIMARY KEY (OrderID, ProductID),
  CONSTRAINT fk_OrderID FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID),
  CONSTRAINT fk_ProductID FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID)
);